name: devfest23
description: "Crafting a language partnet with Flutter and AI"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.2 <4.0.0'

dependencies:

  # -- A
  audioplayers: ^5.2.1

  # -- B
  # -- C
  collection: ^1.18.0

  # -- D
  dart_openai: ^5.0.0
  dio: ^5.4.0

  # -- E

  # -- F
  flex_color_scheme: ^7.3.1

  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.3
  flutter_sound_record: ^3.3.2

  # -- G
  go_router: ^12.1.1

  # -- H
  hooks_riverpod: ^2.4.9

  # -- I
  # -- J
  # -- K
  # -- L
  # -- M
  # -- N
  # -- O
  # -- P
  path: ^1.8.3
  path_provider: ^2.1.1

  # -- Q
  # -- R
  # -- S
  state_notifier: ^1.0.0

  # -- T
  timeago: ^3.5.0

  # -- U
  universal_platform: ^1.0.0+1

  # can't update to 4.x until audioplayers updates
  uuid: ^3.0.7

  # -- V
  # -- W
  wakelock_plus: ^1.1.4

  # -- X
  # -- Y
  # -- Z

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
